"""Admin commands: `python -m flighttracker.cli <command>`."""

import argparse
import getpass
import os
import re
import secrets
import sys
from pathlib import Path

from flighttracker.security.passwords import hash_password

ENV_FILE = Path(".env")
ENV_EXAMPLE_FILE = Path(".env.example")


def _hash_password() -> int:
    password = getpass.getpass("New admin password: ")
    if len(password) < 12:
        print("The password must be at least 12 characters long.", file=sys.stderr)
        return 1
    if password != getpass.getpass("Repeat password: "):
        print("The passwords do not match.", file=sys.stderr)
        return 1
    print("Put this into .env (never commit it!):")
    print(f"ADMIN_PASSWORD_HASH={hash_password(password)}")
    return 0


def _import_airports(if_needed: bool) -> int:
    # Only needs the database, so it also runs in the migrate container without app secrets.
    from flighttracker.db.session import create_db_engine, create_session_factory
    from flighttracker.services.airport_import import import_from_ourairports, import_needed

    database_url = os.environ.get("DATABASE_URL")
    if not database_url:
        print("DATABASE_URL is not set.", file=sys.stderr)
        return 1
    wikidata_contact = os.environ.get("WIKIDATA_CONTACT", "").strip()
    session_factory = create_session_factory(create_db_engine(database_url))
    with session_factory() as session:
        if if_needed and not import_needed(session, wikidata_contact=wikidata_contact):
            print("Airports are already imported.")
            return 0
        try:
            countries, airports, ranked = import_from_ourairports(
                session, wikidata_contact=wikidata_contact
            )
        except Exception as exc:
            print(f"Airport import failed ({type(exc).__name__}).", file=sys.stderr)
            # On automatic startup imports a network problem must not block the app.
            return 0 if if_needed else 1
        session.commit()
    print(f"Imported {countries} countries and {airports} airports ({ranked} with passengers).")
    return 0


def render_dev_env(example: str, password: str) -> str:
    """Local development config from .env.example with fresh random secrets."""
    values = {
        "SECRET_KEY": secrets.token_hex(32),
        "ADMIN_USERNAME": "admin",
        "ADMIN_PASSWORD_HASH": hash_password(password),
        "SESSION_COOKIE_SECURE": "false",
        "FLIGHT_PROVIDER": "google_flights",
    }
    for key, value in values.items():
        example = re.sub(rf"^{key}=.*$", f"{key}={value}", example, flags=re.MULTILINE)
    header = (
        "# Local development only – generated by `python -m flighttracker.cli init-dev-env`.\n"
        f"# Dev login: admin / {password}\n\n"
    )
    return header + example


def _init_dev_env() -> int:
    if ENV_FILE.exists():
        print(".env already exists – nothing changed.")
        return 0
    password = secrets.token_urlsafe(12)
    ENV_FILE.write_text(render_dev_env(ENV_EXAMPLE_FILE.read_text(), password))
    ENV_FILE.chmod(0o600)
    print(f".env created. Login for http://localhost:8000: admin / {password}")
    return 0


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="flighttracker")
    commands = parser.add_subparsers(dest="command", required=True)
    commands.add_parser("hash-password", help="Create a hash for ADMIN_PASSWORD_HASH")
    airports = commands.add_parser(
        "import-airports", help="Load countries, airports and passenger numbers"
    )
    airports.add_argument(
        "--if-needed",
        action="store_true",
        help="Only import when airports (or, with WIKIDATA_CONTACT, passenger numbers) are missing",
    )
    commands.add_parser("init-dev-env", help="Create a .env for local development")
    args = parser.parse_args(argv)
    if args.command == "hash-password":
        return _hash_password()
    if args.command == "init-dev-env":
        return _init_dev_env()
    return _import_airports(args.if_needed)


if __name__ == "__main__":
    sys.exit(main())
